sudo: required
services:
  - docker

before_install:
  - docker build -t chintangajjar/docker-react -f Dockerfile.dev .
 
script:
  - docker run -e CI=true chintangajjar/docker-react npm run start -- --coverage
