sudo: required
services:
  - docker

before_install:
  - docker build -f -t chintangajjar/docker-react Dockerfile.dev .
 
script:
  - docker run chintangajjar/docker-react npm run start -- --coverage
